# Generated by Django 6.1.1 on 2026-09-19 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('self', 'Self'), ('department', 'Department'), ('manager', 'Manager'), ('service', 'Service')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_category', models.CharField(blank=True, max_length=20, null=True)),
                ('was_granted', models.BooleanField()),
                ('reason', models.CharField(max_length=40)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='disclosure.person')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disclosure.requester')),
            ],
            options={
                'ordering': ['-queried_at'],
            },
        ),
        migrations.CreateModel(
            name='DisclosureRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('hr', 'HR'), ('manager', 'Manager'), ('sales_dept', 'Sales'), ('it_dept', 'IT'), ('self', 'Self')], max_length=30)),
                ('field_category', models.CharField(choices=[('personal', 'Personal'), ('employment', 'Employment'), ('location', 'Location'), ('medical', 'Medical')], max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('person', models.ForeignKey(blank=True, help_text='Leave blank for an organisation-wide rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_overrides', to='disclosure.person')),
            ],
            options={
                'ordering': ['relationship', 'field_category'],
                'unique_together': {('person', 'relationship', 'field_category')},
            },
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_category', models.CharField(choices=[('personal', 'Personal'), ('employment', 'Employment'), ('location', 'Location'), ('medical', 'Medical')], max_length=20)),
                ('value', models.TextField()),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='disclosure.person')),
            ],
            options={
                'ordering': ['field_category', 'field_name'],
                'indexes': [models.Index(fields=['person', 'field_name', 'valid_to'], name='disclosure__person__144f4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('hr', 'HR'), ('manager', 'Manager'), ('sales_dept', 'Sales'), ('it_dept', 'IT'), ('self', 'Self')], max_length=30)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='disclosure.person')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='disclosure.requester')),
            ],
            options={
                'ordering': ['-established_at'],
                'indexes': [models.Index(fields=['person', 'requester', 'ended_at'], name='disclosure__person__4c79d6_idx')],
            },
        ),
    ]
