# Generated by Django 6.1.1 on 2026-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disclosurerule',
            options={'ordering': ['relationship', 'field_category', 'field_name']},
        ),
        migrations.AlterUniqueTogether(
            name='disclosurerule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disclosurerule',
            name='field_name',
            field=models.CharField(blank=True, default='', help_text="Leave blank to apply to the whole category. Set to a field name (e.g. 'emergency_contact') to refine one field only.", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='disclosurerule',
            unique_together={('person', 'relationship', 'field_category', 'field_name')},
        ),
    ]
